### ISSUE TITLE
Create Karaoke Rooms

### ISSUE THREAD

**Issue by yskhoo** [RepublicOfKids/SingAlongWithMe#4]
Karaoke rooms can be public/private. We need to come up with a design for how these rooms should look like before implementation.

Users should be able to create a room by selecting a song, the user will be presented with a link and code which they can share with their friends so they can join a room.

**Comment by ryanjadhav** [comment]
Creating persistant rooms would probably require some sort of database. What kind we want? It looks like heroku addons, https://addons.heroku.com/ , have these Free plans:

Redis with 5MB
Mongo with 512MB
Postgres with 10k rows and 20 connections

Theres some more too.

**Comment by yskhoo** [comment]
We just added code for generating a random code for making rooms, as well as Socket IO code for joining rooms. Next step is to allow guests to connect and join these rooms from their device of choice. We need to flesh out the design of these rooms (ex: shorter domain name for joining room, guest limit)

**Comment by ryanjadhav** [comment]
this issue needs to be broken down into smaller more manageable pieces. im going to do that.

**Comment by ryanjadhav** [comment]
creation of rooms is done.
