### ISSUE TITLE
Create developer branch and environment

### ISSUE THREAD

**Issue by yskhoo** [RepublicOfKids/SingAlongWithMe#7]
We have to stop breaking Prod so easily

**Comment by ryanjadhav** [comment]
what's the plan of attack for this?

**Comment by yskhoo** [comment]
Create 'avicii' branch. Super simple! Just run:

git branch avicii (create branch)
git checkout avicii (to use branch)
git push origin avicii ( to let others see it)

This manual was awesome: http://rogerdudler.github.com/git-guide/
